### ISSUE TITLE
[FEATURE] Add a contact page

### ISSUE THREAD

**Issue by Panquesito7** [dev-protocol/devprotocol.xyz#120]
### Detailed description

We should add a contact page where we will add our contact platforms (such as mail, Discord, forum, etc.).

### Context

We can use it for the [config issue template](https://github.com/web3community/devprotocol.xyz/blob/main/.github/ISSUE_TEMPLATE/config.yml) (which is not accepting emails, no idea why) so people can contact us easier and faster. 🙂

### Possible implementation

Add a contact page on the website.

### Additional information

Nope.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krishguptadev** [comment]
Do we have a figma design page for that @vinzvinci

**Comment by vinzvinci** [comment]
Not available for now @krishguptadev

**Comment by krishguptadev** [comment]
> Not available for now @krishguptadev 

Shall we wait in that case?

**Comment by vinzvinci** [comment]
Yes @krishguptadev

**Comment by vinzvinci** [comment]
I'm thinking of having support system just like GitHub Support.
