### ISSUE TITLE
[FEATURE] Responsive Website 2.0

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/devprotocol.xyz#2]
https://www.figma.com/file/rmCKKIsjSWCH0q6lObDQC8/Untitled?node-id=0%3A1

## Tech Stack to use:
- HTML
- Tailwind CSS
- JavaScript
- Suggest JavaScript framework/libraries

## To Do
- Implement the design to code, try to use GitHub pages or you can suggest here

**Comment by mkubdev** [comment]
Hi @web3community ! 🎉🎃

To achieve this issue, you need to clone this repos first, and then make a PR with your changes.

To deploy the website, you can use :
- Any Github Actions deploy script, you can PR yours.
- [Vercel](https://vercel.com/)
- [Netlify](https://www.netlify.com/)

⚡ You should **_only use_** **Tailwind CSS** class.
⚡ You can use any static framework you want (Gatsby, Eleventy, Vue...)
⚡ Don't hesite to **npm init** inside the root folder.

⛔ Please, don't write **_any javascript_** inside your html.


Have fun ! 🎃

**Comment by vinzvinci** [comment]
The thing is, who will start the issue? Please comment below

**Comment by krishguptadev** [comment]
@vinzvinci Assign me, I can do this...

**Comment by vinzvinci** [comment]
Okay go first @krishguptadev

**Comment by vinzvinci** [comment]
Hi @chandresh1339 @NarayanBavisetti,

the coding is started, it is best to chat with the contributors in [discord](https://discord.gg/pb4PA5kdRe), so u can take part.

**Comment by krishguptadev** [comment]
@chandresh1339 @NarayanBavisetti I am gonna make a few issues, That everyone can work upon!
