### ISSUE TITLE
[FEATURE] Create support page 

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/devprotocol.xyz#209]
### Detailed description

Suggested idea on https://trello.com/c/NDxD6XZg/70-documentation-for-a-bug-report

### Context

It can help Dev Protocol followers to report their concern 

### Possible implementation

Idea and it can be copy design: https://tailwindui.com/components/marketing/sections/header#component-547517d4dc48e1bf0ccab051ebb0dcba

### Additional information

if you have suggestions, feel free to comment below

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Simperfy** [comment]
Is there a mockup for this?

**Comment by vinzvinci** [comment]
> Is there a mockup for this? What will be the contents? And what will be the new url subpath (https://devprotocol.xyz/support)?

will try to do it on figma, I'll ping you once it's done

**Comment by vinzvinci** [comment]
Can't edit well. I think u can continue this, let me handle the content, you can use the content there
![image](https://user-images.githubusercontent.com/73097560/159766760-90e2b1d1-0a46-48f7-8ff7-068775c15ee9.png)

**Comment by gptkrsh** [comment]
Hi @vinzvinci can you please share where the contact links are to point to make it easier for contributors?

**Comment by vinzvinci** [comment]
We used 3 email @krshkodes for communications
For general issue: hi@devprotocol.xyz
For security issue: security@devprotocol.xyz
For community related issue: community@devprotocol.xyz
