### ISSUE TITLE
[OTHER] Does this page use the latest NodeJS version?

### ISSUE THREAD

**Issue by Panquesito7** [dev-protocol/devprotocol.xyz#225]
### What would you like to share?

The readme states the latest NodeJS version.
Is the latest NodeJS version actually compatible with this page or is it a specific NodeJS version?

Thank you.

### Would you like to work on this issue?

- [ ] Yes, I want to work on this issue!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gptkrsh** [comment]
The latest nodejs version will be compatible with this since there hasn't been any major update to nodejs that breaks previous code and even if in such case, our framework is a well maintained one which keeps up with all releases.

**Comment by gptkrsh** [comment]
I hope that answers this question, if you have any other queries please type back on this issue, closing for now
