### ISSUE TITLE
[FEATURE] Use the prettier plugin

### ISSUE THREAD

**Issue by vinzvinci** [dev-protocol/devprotocol.xyz#90]
### Detailed description

Aggre asked this before to add **Prettier** plugin to automatically format the code

### Context

CC @krishguptadev 

### Possible implementation

https://github.com/snowpackjs/prettier-plugin-astro

### Additional information

![image](https://user-images.githubusercontent.com/73097560/139607470-f9c1f9e3-fc0d-4b66-a109-0ab72dcce7db.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by krishguptadev** [comment]
Buil code should not be formatted for performance reasons, I could add it to the src if you like 🙂

**Comment by vinzvinci** [comment]
Okay if it will affect the performance @krishguptadev, let's not add it.

**Comment by krishguptadev** [comment]
So add it to the source or not?

**Comment by vinzvinci** [comment]
If this was added to the source, it won't affect much right?

**Comment by krishguptadev** [comment]
> If this was added to the source, it won't affect much right?

Would enforce a code style, that's it

**Comment by vinzvinci** [comment]
Okay, you can add it.

**Comment by krishguptadev** [comment]
The [Plugin](https://github.com/snowpackjs/prettier-plugin-astro) is WIP, so we need to wait a while before it is prod released.

**Comment by mkubdev** [comment]
HI, the plugin is working like a charm now: https://github.com/withastro/prettier-plugin-astro

**Comment by gptkrsh** [comment]
I've opened a PR so that this issue is finally closed

**Comment by gptkrsh** [comment]
We might want to upgrade to Astrov2 before this gets implemented just saying though
